### Create a new product (requires Admin token)
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbnVzZXIxQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzE5ODY5MDk2LCJleHAiOjE3MTk4NzI2OTZ9.PaxgNjGf8v7VSMzLEKBkdvTw_F0IwpPLTbXKNW_X8Mw

{
    "name": "P3",
    "description": "This is category 9",
    "price": 1000.99,
    "image": "https://image14.photobiz.com/9488/8_20190710140611_10464503_large.jpg",
    "stockQuantity": 4,
    "categoryId": 9
}

### Get all products
GET http://localhost:3000/products

### Get a specific product
GET http://localhost:3000/products/5

### Update a product (requires Admin token)
PUT http://localhost:3000/products/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbnVzZXIxQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzE5OTIxNzY4LCJleHAiOjE3MTk5MjUzNjh9._W5COEdL7LkDeH1MTtKyvntiaH4mkHETrDtAcOqRt_U

{
    "name": "The New Product",
    "description": "This is an new product",
    "price": 70.99,
    "image": "http://example.com/newimage.jpg",
    "stockQuantity": 20,
    "categoryId": 1
}

### Delete a product (requires Admin token)
DELETE http://localhost:3000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbnVzZXIxQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzE5ODgxODg3LCJleHAiOjE3MTk4ODU0ODd9.MpgNYdIRAaSCr_xP3b3kbTSBymKcx_2CUQ7wlnCaGGQ





# ### Create a new product with image (requires Admin token)
# POST http://localhost:3000/products
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbnVzZXIxQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzE5NzYwMzI5LCJleHAiOjE3MTk3NjM5Mjl9.1l7NMF1xp19zF4rQOgEXf89y_mClYBCWAxZGrd-Rfgk
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="name"

# Test Product Upload
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="description"

# This is a product tests image upload.
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="price"

# 109.99
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="stockQuantity"

# 7
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="categoryId"

# 1
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="image"; filename="test_image.jpg"
# Content-Type: image/jpeg

# <image content>
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--

